config/routes.rb
Deliveryboy::Application.routes.draw do
  get "links/*args/:link/:history/unsubscribe" => "links#unsubscribe"
  get "links/:link/:history/unsubscribe" => "links#unsubscribe", :args => []
  get "links/*args/:link/:history/:activity" => "links#visit"
  get "links/:link/:history/:activity" => "links#visit", :args => []

  resources :email_histories do
    collection do
      get 'bounced'
      get 'visited'
    end
  end

  resources :email_addresses
  match 'apis(/:action(/:id(.:format)))', :controller => 'apis'

end

app/models/email_history.rb
require 'uuid'

class EmailHistory < ActiveRecord::Base
  belongs_to :to, :class_name => 'EmailAddress', :foreign_key => 'to_email_id'
  belongs_to :from, :class_name => 'EmailAddress', :foreign_key => 'from_email_id'
  scope :visited, where("visit_at IS NOT NULL")
  scope :opened, where("open_at IS NOT NULL")
  scope :bounced, where("bounce_at IS NOT NULL")
  before_create :set_unique
  def to_param
    self.unique
  end
  def set_unique
    self.unique = UUID.new.generate
  end
end

app/controllers/email_histories_controller.rb
class EmailHistoriesController < ApplicationController
  # GET /email_histories
  # GET /email_histories.xml
  def index(klass = EmailHistory)
    @email_histories = klass.order('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html { render :action => 'index' }
      format.xml  { render :xml => @email_histories }
    end
  end

  def bounced
    index(EmailHistory.bounced)
  end

  def visited
    index(EmailHistory.visited)
  end

  # GET /email_histories/1
  # GET /email_histories/1.xml
  def show
    @email_history = EmailHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @email_history }
    end
  end

  # GET /email_histories/new
  # GET /email_histories/new.xml
  def new
    @email_history = EmailHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @email_history }
    end
  end

  # GET /email_histories/1/edit
  def edit
    @email_history = EmailHistory.find(params[:id])
  end

  # POST /email_histories
  # POST /email_histories.xml
  def create
    @email_history = EmailHistory.new(params[:email_history])

    respond_to do |format|
      if @email_history.save
        format.html { redirect_to(@email_history, :notice => 'Email history was successfully created.') }
        format.xml  { render :xml => @email_history, :status => :created, :location => @email_history }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @email_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /email_histories/1
  # PUT /email_histories/1.xml
  def update
    @email_history = EmailHistory.find(params[:id])

    respond_to do |format|
      if @email_history.update_attributes(params[:email_history])
        format.html { redirect_to(@email_history, :notice => 'Email history was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @email_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /email_histories/1
  # DELETE /email_histories/1.xml
  def destroy
    @email_history = EmailHistory.find(params[:id])
    @email_history.destroy

    respond_to do |format|
      format.html { redirect_to(email_histories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/email_histories_helper.rb
module EmailHistoriesHelper
end

app/views/email_histories/_form.html.erb
<%= form_for(@email_history) do |f| %>
  <% if @email_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_history.errors.count, "error") %> prohibited this email_history from being saved:</h2>

      <ul>
      <% @email_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_email_id %><br />
    <%= f.text_field :to_email_id %>
  </div>
  <div class="field">
    <%= f.label :from_email_id %><br />
    <%= f.text_field :from_email_id %>
  </div>
  <div class="field">
    <%= f.label :message_id %><br />
    <%= f.text_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :open_at %><br />
    <%= f.datetime_select :open_at %>
  </div>
  <div class="field">
    <%= f.label :visit_at %><br />
    <%= f.datetime_select :visit_at %>
  </div>
  <div class="field">
    <%= f.label :bounce_at %><br />
    <%= f.datetime_select :bounce_at %>
  </div>
  <div class="field">
    <%= f.label :bounce_reason %><br />
    <%= f.text_field :bounce_reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_histories/edit.html.erb
<h1>Editing email_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_history %> |
<%= link_to 'Back', email_histories_path %>

app/views/email_histories/index.html.erb
<h1>Listing email_histories</h1>

<table>
  <tr>
    <th>To email</th>
    <th>From email</th>
    <th>Message</th>
    <th>Open at</th>
    <th>Visit at</th>
    <th>Bounce at</th>
    <th>Bounce reason</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @email_histories.each do |email_history| %>
  <tr>
    <td><%= email_history.to_email_id %></td>
    <td><%= email_history.from_email_id %></td>
    <td><%= email_history.message_id %></td>
    <td><%= email_history.open_at %></td>
    <td><%= email_history.visit_at %></td>
    <td><%= email_history.bounce_at %></td>
    <td><%= email_history.bounce_reason %></td>
    <td><%= link_to 'Show', email_history %></td>
    <td><%= link_to 'Edit', edit_email_history_path(email_history) %></td>
    <td><%= link_to 'Destroy', email_history, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @email_histories %>

<br />

<%= link_to 'New Email history', new_email_history_path %>

app/views/email_histories/new.html.erb
<h1>New email_history</h1>

<%= render 'form' %>

<%= link_to 'Back', email_histories_path %>

app/views/email_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>To email:</b>
  <%= @email_history.to_email_id %>
</p>

<p>
  <b>From email:</b>
  <%= @email_history.from_email_id %>
</p>

<p>
  <b>Message:</b>
  <%= @email_history.message_id %>
</p>

<p>
  <b>Open at:</b>
  <%= @email_history.open_at %>
</p>

<p>
  <b>Visit at:</b>
  <%= @email_history.visit_at %>
</p>

<p>
  <b>Bounce at:</b>
  <%= @email_history.bounce_at %>
</p>

<p>
  <b>Bounce reason:</b>
  <%= @email_history.bounce_reason %>
</p>


<%= link_to 'Edit', edit_email_history_path(@email_history) %> |
<%= link_to 'Back', email_histories_path %>