config/routes.rb
Deliveryboy::Application.routes.draw do
  get "links/*args/:link/:history/unsubscribe" => "links#unsubscribe"
  get "links/:link/:history/unsubscribe" => "links#unsubscribe", :args => []
  get "links/*args/:link/:history/:activity" => "links#visit"
  get "links/:link/:history/:activity" => "links#visit", :args => []

  resources :email_histories do
    collection do
      get 'bounced'
      get 'visited'
    end
  end

  resources :email_addresses
  match 'apis(/:action(/:id(.:format)))', :controller => 'apis'

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  # GET /email_addresses
  # GET /email_addresses.xml
  def index
    @email_addresses = EmailAddress.order('created_at DESC').page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @email_addresses }
    end
  end

  # GET /email_addresses/1
  # GET /email_addresses/1.xml
  def show
    @email_address = EmailAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @email_address }
    end
  end

  # GET /email_addresses/new
  # GET /email_addresses/new.xml
  def new
    @email_address = EmailAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @email_address }
    end
  end

  # GET /email_addresses/1/edit
  def edit
    @email_address = EmailAddress.find(params[:id])
  end

  # POST /email_addresses
  # POST /email_addresses.xml
  def create
    @email_address = EmailAddress.new(params[:email_address])

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to(@email_address, :notice => 'Email address was successfully created.') }
        format.xml  { render :xml => @email_address, :status => :created, :location => @email_address }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @email_address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /email_addresses/1
  # PUT /email_addresses/1.xml
  def update
    @email_address = EmailAddress.find(params[:id])

    respond_to do |format|
      if @email_address.update_attributes(params[:email_address])
        format.html { redirect_to(@email_address, :notice => 'Email address was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @email_address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.xml
  def destroy
    @email_address = EmailAddress.find(params[:id])
    @email_address.destroy

    respond_to do |format|
      format.html { redirect_to(email_addresses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/email_addresses_helper.rb
module EmailAddressesHelper
end

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <% if @email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% @email_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :unique %><br />
    <%= f.text_field :unique %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Editing email_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_address %> |
<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/index.html.erb
<h1>Listing email_addresses</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Unique</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @email_addresses.each do |email_address| %>
  <tr>
    <td><%= email_address.email %></td>
    <td><%= email_address.unique %></td>
    <td><%= link_to 'Show', email_address %></td>
    <td><%= link_to 'Edit', edit_email_address_path(email_address) %></td>
    <td><%= link_to 'Destroy', email_address, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @email_addresses %>

<br />

<%= link_to 'New Email address', new_email_address_path %>

app/views/email_addresses/new.html.erb
<h1>New email_address</h1>

<%= render 'form' %>

<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @email_address.email %>
</p>

<p>
  <b>Unique:</b>
  <%= @email_address.unique %>
</p>


<%= link_to 'Edit', edit_email_address_path(@email_address) %> |
<%= link_to 'Back', email_addresses_path %>